on:
  push:
    branches:
      - main  

name: deploy

jobs:
  deploy:
    name: deploy cloud run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        env:
          PORT: ${{ env.PORT }}
        run: |
          echo "PORT=${PORT}" > .env

      - name: Build and push to Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: francoruti/prueba
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}